# Generated by Django 4.1.4 on 2022-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=400)),
                ('Message', models.TextField()),
            ],
        ),
    ]
